services:
  rabbitmq:
    build:
      context: .
      dockerfile: dockerfile.rabbitmq
    tmpfs:
      - /tmp/rabbitmq
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 5s
      timeout: 2s
      retries: 5

  publisher:
    build:
      context: .
      dockerfile: publisherApp/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"  # Exposing port 8080

  consumer:
    build:
      context: .
      dockerfile: consumerApp/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

  externalservice:
    build:
      context: .
      dockerfile: externalServiceApp/Dockerfile
    ports:
      - "8081:8081"  # Exposing port 8081