# Use the official Golang image
FROM golang:1.22

# Set the Current Working Directory inside the container
WORKDIR /consumerApp

# Copy go.mod and go.sum files into the working directory
COPY consumerApp/go.mod consumerApp/go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code into the working directory
COPY consumerApp/ .

# Build the application
RUN go build -o consumer .

# Command to run the executable
CMD ["./consumer"]
